### ISSUE TITLE
Got error "Error [ERR_REQUIRE_ESM]: require() of ES Module not supported"

### ISSUE THREAD

**Issue by Mr4sR** [nsiregar/shpee-js#1]
Got error "Error [ERR_REQUIRE_ESM]: require() of ES Module not supported" from "shpee-js/lib/index.cjs"

**Comment by nsiregar** [comment]
What node version are you using?

**Comment by Mr4sR** [comment]
> What node version are you using?

My node version : v14.17.3
My npm version : 8.3.0

**Comment by Mr4sR** [comment]
> What node version are you using?

Here the error :
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\MIXXING\ASRBot\node_modules\shpee\node_modules\node-fetch\src\index.js
require() of ES modules is not supported.
require() of C:\Users\MIXXING\ASRBot\node_modules\shpee\node_modules\node-fetch\src\index.js from C:\Users\MIXXING\ASRBot\node_modules\shpee\lib\index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\MIXXING\ASRBot\node_modules\shpee\node_modules\node-fetch\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\MIXXING\ASRBot\node_modules\shpee\lib\index.cjs:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'ERR_REQUIRE_ESM'
}
```
